# Generated by Django 2.2.5 on 2019-09-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_parse',
            field=models.BooleanField(default=False),
        ),
    ]
